config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/dashboard', to:'dashboard#show', as: 'dashboard'

  resources :users, only: [:index, :show] do
    resources :recognitions, only:[:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recognition.rb
class Recognition < ApplicationRecord

  belongs_to :recognizer, class_name: 'User'
  belongs_to :recognized, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :recognitions_gave, class_name: 'Recognition', foreign_key: :recognizer_id
has_many :recognitions_recieved, class_name: 'Recognition', foreign_key: :recognized_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

def show
  # making the controller to show the names and recognitions descriptions in the dashboard
  @user = current_user
  # This will make sure that when listing all the employees if the user is logged in it wont list themselves
  @employees = User.all.reject{ |user| user == @user}
  @recognitions_gave = @user.recognitions_gave
  @recognitions_recieved = @user.recognitions_recieved
end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # Show latest Recognition given by the authenticated user
    @recognitions_gave = Recognition.last(1)
  end
end

app/controllers/recognitions_controller.rb
class RecognitionsController < ApplicationController
  def new
    # initialize a recogntion instance
    @recognition = Recognition.new
  end

  def create
    # Create Recognition
    @recognition = Recognition.new(recognition_params)
    @recognition.recognizer = current_user
    @recognition.recognized = User.find(params[:user_id])
    @recognition.save
    # @recognition_recognized = @user.description
    # @recognition.recognizer = current_user
    #when a new Recognition is saved redirect to users dashboard
    redirect_to dashboard_path
  end

  def edit
    @recognition = Recognition.find(params[:id])
  end

  private

  # make parameters for User and recognition creations
  def set_user
    @user = User.find(params[:id])
  end

  def recognition_params
    params.require(:recognition).permit(:name, :description)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recognitions = @user.recognitions
    
  end

  private

  def set_user
    @user = User.find([params[:id]])
  end
end


# has_many :recognitions
# has_many :recognizer, class_name: 'Recognition', foreign_key: :recognizer_id
# has_many :recognitions, class_name: 'Recognition', foreign_key: :recognized_id

# belongs_to :recognizer, class_name: 'User'
# belongs_to :recognized, class_name: 'User'

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recognitions_helper.rb
module RecognitionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/show.html.erb
<div class="container">
  <h1>Dashboard</h1>

  <h1>List of employees</h1>
  <%= render 'users/employees' %>
  <h1>Recent Recognitions Given</h1>
  <%= render 'recognitions/card' %>
  <h1>Recognitions Recieved</h1>
  <%= render 'recognitions/recieved_card' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiferayAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_header.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Welcome to the Employee Recognitinon page!</h1>
    <p>Want to recogognize an employee for somethinng?</p>
    <% if user_signed_in? %>
      <%= link_to  "To your dashboard", dashboard_path, class: 'btn btn-primary' %>
    <% else %>
      <%= link_to  "Sign in", new_user_session_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'header' %>

<div class="container">
  <h3>Your recent recognitions</h3>
  
  <div class="cards-index-columns">
    <% @recognitions_gave.each do |recognition| %>
      <%= render 'recognitions/card', recognition: recognition %>
    <% end %>
  </div>

</div>

app/views/recognitions/_card.html.erb
<div class="card card-index-sm" style="">
  <% @recognitions_gave.each do |recognition| %>
    <h4><%= recognition.recognized.name %></h4>
    <p><strong><%= recognition.name %>:</strong> <%= recognition.description %></p>
  <% end %>
</div>

app/views/recognitions/_recieved_card.html.erb
<div class="card card-index-sm" style="">
  <% @recognitions_recieved.each do |recognition| %>
    <h4><%= recognition.recognizer.name %></h4>
    <p><strong><%= recognition.name %>:</strong> <%= recognition.description %></p>
  <% end %>
</div>

app/views/recognitions/new.html.erb
<div class='form-card'>
  <%= form_for [User.find(params[:user_id]), @recognition] do |f| %>
    <%= f.label :name, "What is this skill you want to recognize?" %>
    <%= f.text_field :name %>
    <%= f.label :description, "What kind of recognition do you want to give him/her?" %>
    <%= f.text_field :description %>
    <%= f.submit %>
  <% end %>
</div>  

app/views/shared/_alert.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand d-flex" href="/">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
  </a>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
</div>

app/views/users/_employees.html.erb
  <div class="card card-index-sm">
    <% @employees.each do |employee| %>
      <%= link_to new_user_recognition_path(employee) do %>
        <h3><%= employee.name %></h3>
      <% end %>
    <% end %>
  
  </div>

app/views/users/index.html.erb
 <% @users.each do |user| %>
    <h4><%= user.name %> </h4>
    <ul>
      <% user.recognitions_gave.each do |recognition| %>
      <li><%= recognition.name %>. <%= recognition.description %></li>
      <% end %>
    </ul>
  <% end %>

app/views/users/show.html.erb
<%= @user.name %>